### ISSUE TITLE
Is it in your plans to add scripting support?

### ISSUE THREAD

**Issue by fabiocaccamo** [LucasLorentz/AS3SVGRenderer#52]

**Comment by LucasLorentz** [comment]
No. It isn't.

It would be too hard to add support for scripts as defined in the svg specification.

But today the loaded svg can be modified by as3 code. Properties, styles and structure can be modified using the available methods/properties. And you can listen to flash display object events.

If you want a permanent script. Just do it in as3 after loading the svg.

If you want a dynamic script. You can load some as3 script with the svg and execute it using tamarin esc compiler or any other evaluator for as3.

http://stackoverflow.com/questions/5845439/how-do-i-call-the-tamarin-esc-compiler-from-as3-code

PS: tamarin esc compiler would not work on ios because it generates and loads an assembly with code. And I don't think apple allows that.
